import {describe,it,expect,vi} from 'vitest';
import {database} from './db-harness';
import {previousTurkeyDay,previewCommandMediaRetention,runCommandMediaRetention,expiredCommandMediaKeys,retentionSealedJob} from '../src/commands/media-retention';
import {READER_TEMPLATES,getReaderJob,getReaderMedia} from '../src/commands/reader';
const now=Date.parse('2026-09-30T09:00:00Z');
const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(){
 const db=database(),objects=new Map();
 const media={list:vi.fn(async({prefix,limit,cursor})=>{const all=[...objects.values()].filter(o=>o.key.startsWith(prefix)&&(!cursor||o.key>cursor)).sort((a,b)=>a.key.localeCompare(b.key));const page=all.slice(0,limit);return {objects:page,truncated:all.length>limit,cursor:page.at(-1)?.key};}),delete:vi.fn(async k=>{objects.delete(k);}),get:vi.fn(async()=>null)};
 const env={...db.env,COMMAND_MEDIA:media,COMMAND_MEDIA_RETENTION_MODE:'delete'};
 function job(n,overrides={}) {const j={id:uuid(n),template:READER_TEMPLATES.terane,status:'completed',created:'2026-09-29 08:00:00',finished:'2026-09-29 09:00:00',notified:'2026-09-29 09:01:00',...overrides};
 db.sql.prepare('INSERT INTO command_jobs(id,template_id,name,steps_json,status,created_at,finished_at,notified_at) VALUES (?,?,?,?,?,?,?,?)').run(j.id,j.template,'fixture',JSON.stringify([{botUsername:'fixture_bot',command:'/fixture',delaySeconds:3}]),j.status,j.created,j.finished,j.notified);return j.id;}
 function file(id,leaf='image.png',kind='image/png'){const key=`commands/${id}/${leaf}`;objects.set(key,{key,size:42,httpMetadata:{contentType:kind}});return key;}
 function result(id,key,text='Fixture preserved text'){db.sql.prepare("INSERT INTO command_results(job_id,step_index,bot_username,command,response_text,response_kind,media_key) VALUES (?,0,'fixture_bot','/fixture',?,'image',?)").run(id,text,key);}
 return {...db,env,objects,media,job,file,result};
}
describe('narrow previous Turkey day media retention',()=>{
 it('uses Turkey midnight, including exact 21:00 UTC transition',()=>{expect(previousTurkeyDay(Date.parse('2026-09-29T20:59:59Z'))).toEqual({day:'2026-09-28',from:'2026-09-27 21:00:00',until:'2026-09-28 21:00:00'});expect(previousTurkeyDay(Date.parse('2026-09-29T21:00:00Z'))).toEqual({day:'2026-09-29',from:'2026-09-28 21:00:00',until:'2026-09-29 21:00:00'});});
 it('default off needs neither migration nor storage access',async()=>{const env={DB:{prepare:vi.fn()},COMMAND_MEDIA:{list:vi.fn()}};expect(await runCommandMediaRetention(env,now)).toEqual({mode:'off'});expect(env.DB.prepare).not.toHaveBeenCalled();});
 it('dry-run lists exact images and merged PDF without any writes or body reads',async()=>{const f=fixture();try{const id=f.job(1),image=f.file(id),pdf=f.file(id,'fixture-sonuclari.pdf','application/pdf');f.file(id,'keep.txt','text/plain');f.result(id,image);const before=f.sql.prepare('SELECT * FROM command_results').all();const report=await previewCommandMediaRetention(f.env,now);expect(report.jobs[0].files.map(x=>x.key)).toEqual([pdf,image].sort());expect(report.eligible_jobs).toBe(1);expect(f.media.delete).not.toHaveBeenCalled();expect(f.media.get).not.toHaveBeenCalled();expect(f.sql.prepare('SELECT COUNT(*) n FROM command_media_expirations').get().n).toBe(0);expect(f.sql.prepare('SELECT * FROM command_results').all()).toEqual(before);expect(f.sql.prepare("SELECT COUNT(*) n FROM system_state WHERE key LIKE 'command_media_retention:%'").get().n).toBe(0);}finally{f.sql.close();}});
 it('selects only all three allowed terminal templates on the previous day',async()=>{const f=fixture();try{for(const [i,template] of Object.values(READER_TEMPLATES).entries()){const id=f.job(i+1,{template});f.file(id);}f.job(5,{template:'e36042c7-799a-4843-8525-fcba34a66d68'});f.job(6,{created:'2026-09-30 08:00:00'});f.job(7,{created:'2026-09-28 08:00:00'});f.job(8,{status:'queued'});f.job(9,{status:'leased'});const report=await previewCommandMediaRetention(f.env,now);expect(report.eligible_jobs).toBe(3);expect(report.has_more_jobs).toBe(true);expect(report.jobs).toHaveLength(2);}finally{f.sql.close();}});
 it('protects active workflow media, notification retries and recent terminal jobs',async()=>{const f=fixture();try{const active=f.job(1);f.sql.prepare("INSERT INTO command_workflows(id,owner_sub,request_key,mode,status,snapshots_json,current_job_id,requested_at,accepted_at,start_before,deadline_at) VALUES ('workflow','owner','key','market_round','running',?,?,'x','x','x','x')").run(JSON.stringify([{job_id:active}]),active);f.job(2,{notified:null,finished:'2026-09-29 12:00:00'});f.job(3,{finished:'2026-09-30 08:30:00'});const delivering=f.job(4);f.sql.prepare("INSERT INTO command_deliveries(job_id,part,status,updated_at) VALUES (?,'pdf','processing','2026-09-30 08:59:00')").run(delivering);f.file(delivering);f.file(active);expect((await previewCommandMediaRetention(f.env,now)).eligible_jobs).toBe(0);}finally{f.sql.close();}});
 it('deletes images/PDF only, keeps all text rows and unrelated objects; expired access returns 410',async()=>{const f=fixture();try{const id=f.job(1),image=f.file(id),pdf=f.file(id,'merged.pdf','application/pdf'),txt=f.file(id,'keep.txt','text/plain');f.objects.set('kap/keep.pdf',{key:'kap/keep.pdf',size:1});f.result(id,image);const before=f.sql.prepare('SELECT * FROM command_results').all();expect((await runCommandMediaRetention(f.env,now)).deleted_objects).toBe(2);expect(f.objects.has(image)).toBe(false);expect(f.objects.has(pdf)).toBe(false);expect(f.objects.has(txt)).toBe(true);expect(f.objects.has('kap/keep.pdf')).toBe(true);expect(f.sql.prepare('SELECT * FROM command_results').all()).toEqual(before);expect(await retentionSealedJob(f.env,id)).toBe(true);const read=await getReaderJob(f.env,id,now);expect(read.full_text).toContain('Fixture preserved text');expect(read.results[0].media_state).toBe('expired');expect(read.result_set_complete).toBe(false);await expect(getReaderMedia(f.env,id,before[0].id)).rejects.toMatchObject({code:'media_expired',status:410});expect(f.media.get).not.toHaveBeenCalled();f.env.COMMAND_MEDIA_RETENTION_MODE='off';expect((await expiredCommandMediaKeys(f.env,[image])).has(image)).toBe(true);expect(await retentionSealedJob(f.env,id)).toBe(true);}finally{f.sql.close();}});
 it('bounds pages at 20 objects and follows the cursor without skipping after deletion',async()=>{const f=fixture();try{const id=f.job(1);for(let i=0;i<25;i++)f.file(id,`${String(i).padStart(2,'0')}.png`);expect((await previewCommandMediaRetention(f.env,now)).jobs[0].has_more).toBe(true);expect((await runCommandMediaRetention(f.env,now)).deleted_objects).toBe(20);expect((await runCommandMediaRetention(f.env,now+60000)).deleted_objects).toBe(5);expect(f.objects.size).toBe(0);expect(f.media.list.mock.calls.every(([args])=>args.limit===20)).toBe(true);}finally{f.sql.close();}});
 it('does not delete malformed nested or traversal keys',async()=>{const f=fixture();try{const id=f.job(1);f.file(id,'../bad.pdf');f.file(id,'nested/bad.pdf');f.file(id,'..bad.pdf');expect((await runCommandMediaRetention(f.env,now)).deleted_objects).toBe(0);expect(f.objects.size).toBe(3);}finally{f.sql.close();}});
 it('records bounded failures, stops after three attempts and retains source text',async()=>{const f=fixture();try{const id=f.job(1),key=f.file(id);f.result(id,key);f.media.delete.mockImplementation(async()=>{throw new Error('private provider diagnostic');});for(let i=0;i<5;i++)await runCommandMediaRetention(f.env,now+i*60000);expect(f.media.delete).toHaveBeenCalledTimes(3);const audit=f.sql.prepare('SELECT * FROM command_media_expirations').get();expect(audit.status).toBe('error');expect(audit.error).toBe('r2_delete_or_audit_failed');expect(audit.attempts).toBe(3);expect(f.sql.prepare('SELECT response_text FROM command_results').get().response_text).toBe('Fixture preserved text');expect(f.objects.has(key)).toBe(true);}finally{f.sql.close();}});
 it('reconciles a pending deletion audit before advancing R2 pagination',async()=>{const f=fixture();try{const id=f.job(1),key=f.file(id);f.sql.prepare("INSERT INTO command_media_expirations(media_key,job_id,job_trt_day,status,size_bytes,planned_at) VALUES (?,?,'2026-09-29','pending',42,'x')").run(key,id);f.objects.delete(key);expect((await runCommandMediaRetention(f.env,now)).deleted_objects).toBe(1);expect(f.media.list).not.toHaveBeenCalled();expect(f.sql.prepare('SELECT status FROM command_media_expirations').get().status).toBe('deleted');}finally{f.sql.close();}});
 it('concurrent cleanup uses one global lease',async()=>{const f=fixture();try{const id=f.job(1);f.file(id);const runs=await Promise.all([runCommandMediaRetention(f.env,now),runCommandMediaRetention(f.env,now)]);expect(runs.filter(x=>x.mode==='busy')).toHaveLength(1);expect(f.media.delete).toHaveBeenCalledTimes(1);}finally{f.sql.close();}});
 it('dry-run cron reviews every bounded page/job without deleting any files',async()=>{const f=fixture();try{for(let n=1;n<=3;n++){const id=f.job(n);for(let i=0;i<25;i++)f.file(id,`${String(i).padStart(2,'0')}.png`);}f.env.COMMAND_MEDIA_RETENTION_MODE='dry_run';for(let i=0;i<5;i++)await runCommandMediaRetention(f.env,now+i*60000);const reports=f.sql.prepare("SELECT value FROM system_state WHERE key LIKE 'command_media_retention:preview-job:%'").all().map(r=>JSON.parse(r.value));expect(reports).toHaveLength(3);expect(reports.every(r=>r.files.length===25&&!r.has_more)).toBe(true);expect(f.objects.size).toBe(75);expect(f.media.delete).not.toHaveBeenCalled();expect(f.media.list.mock.calls.every(([x])=>x.limit===20)).toBe(true);}finally{f.sql.close();}});
 it('cron dry-run records a private report while preserving files',async()=>{const f=fixture();try{f.file(f.job(1));f.env.COMMAND_MEDIA_RETENTION_MODE='dry_run';await runCommandMediaRetention(f.env,now);expect(f.media.delete).not.toHaveBeenCalled();expect(f.sql.prepare("SELECT value FROM system_state WHERE key='command_media_retention:preview'").get()).toBeTruthy();expect(f.objects.size).toBe(1);}finally{f.sql.close();}});
});
