import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {database} from './db-harness';
import {runEveningSummaries,eveningTradingDay,eveningWindow,scheduledSummaryId,summaryStateKey,getEveningDkbSummary} from '../src/telegram/evening-summary';
import {deliverOne} from '../src/telegram/outbox';
import {TelegramError,sendMessage} from '../src/telegram/client';
vi.mock('../src/telegram/client',async original=>({...await original(),sendMessage:vi.fn(async()=>123),sendDocument:vi.fn()}));
let sql,env;
const at=Date.parse('2026-09-30T17:30:00Z');
beforeEach(()=>{({sql,env}=database());env.EVENING_SUMMARY_ENABLED='true';vi.useFakeTimers();vi.setSystemTime(at);sendMessage.mockReset().mockResolvedValue(123);});
afterEach(()=>{sql.close();vi.useRealTimers();});
const state=()=>JSON.parse(sql.prepare('SELECT value FROM system_state WHERE key=?').get(summaryStateKey(env.TELEGRAM_CHAT_ID,'2026-09-30')).value);
const rows=()=>sql.prepare("SELECT * FROM telegram_outbox WHERE id LIKE 'day-summary:auto:%' ORDER BY id").all();
function manyBreakers(){for(let i=0;i<550;i++){const code='A'+String(i).padStart(4,'0');sql.prepare('INSERT INTO kap_disclosures(disclosure_id,title,ticker,published_at,url,content_hash,metadata_json) VALUES (?,?,?,?,?,?,?)').run(String(i),'Pay Bazında Devre Kesici Bildirimi',code,'2026-09-30T10:00:00Z','https://www.kap.org.tr/tr/Bildirim/'+i,'evening'+i,JSON.stringify({subjectCodes:[code]}));}}
async function sent(id){sql.prepare("UPDATE telegram_outbox SET status='sent',sent_at='2026-09-30 17:31:00',message_id=123 WHERE id=?").run(id);}
describe('native sequential evening summaries',()=>{
 it('runs only inside Turkey 20:30–21:00; skips holidays/weekends and unknown-year calendars',async()=>{expect(eveningWindow(at-1).open).toBe(false);expect(eveningWindow(at).open).toBe(true);expect(eveningWindow(Date.parse('2026-09-30T18:00:00Z')).open).toBe(false);expect(eveningTradingDay(env,Date.parse('2026-10-29T17:30:00Z'))).toBe('closed');expect(eveningTradingDay(env,Date.parse('2026-10-28T17:30:00Z'))).toBe('open');expect(eveningTradingDay(env,Date.parse('2026-10-03T17:30:00Z'))).toBe('closed');expect(eveningTradingDay(env,Date.parse('2027-01-04T17:30:00Z'))).toBe('calendar_unverified');expect(await runEveningSummaries(env,at-1)).toEqual({status:'outside_window'});expect(rows()).toHaveLength(0);});
 it('defaults disabled and creates no state/pages',async()=>{env.EVENING_SUMMARY_ENABLED=undefined;expect(await runEveningSummaries(env,at)).toEqual({status:'disabled'});expect(rows()).toHaveLength(0);});
 it('rejects malformed or unofficial calendar overrides without starting',async()=>{for(const c of ['bad',JSON.stringify({year:2026,source:'https://untrusted.test',verifiedAt:'2026-01-01',closedDates:[]}),JSON.stringify({year:2026,source:'https://www.borsaistanbul.com/resmi-tatil-gunleri',verifiedAt:'2026-01-01',closedDates:['2026-02-30']})]){env.EVENING_SUMMARY_CALENDAR_JSON=c;expect(await runEveningSummaries(env,at)).toEqual({status:'calendar_unverified'});}expect(rows()).toHaveLength(0);});
 it('date keys deduplicate concurrent ticks, all DKB pages must be sent and PAY is never scheduled',async()=>{manyBreakers();const runs=await Promise.all(Array.from({length:6},()=>runEveningSummaries(env,at)));expect(runs.filter(r=>r.status==='dkb_pending')).toHaveLength(1);const dkb=rows();expect(dkb.length).toBeGreaterThan(1);expect(dkb.every(r=>r.id.includes(':dkb:'))).toBe(true);expect(JSON.parse(dkb[0].payload)).not.toHaveProperty('replyTo');await sent(dkb[0].id);await runEveningSummaries(env,at+60000);expect(state().status).toBe('dkb_pending');for(const r of dkb.slice(1))await sent(r.id);await runEveningSummaries(env,at+120000);expect(state().status).toBe('completed');const count=rows().length;await runEveningSummaries(env,at+240000);expect(rows()).toHaveLength(count);expect(rows().some(r=>r.id.includes(':pay:'))).toBe(false);});
 it('sends only scheduled DKB pages in order through the real outbox and makes its result readable',async()=>{manyBreakers();await runEveningSummaries(env,at);const dkb=rows();const before=await getEveningDkbSummary(env,'2026-09-30',at);expect(before.availability).toBe('pending');expect(before.shares).toHaveLength(550);expect(before.total_source_records).toBe(550);expect(before.next_source_offset).toBe(100);expect(before.full_text).toContain('Devre kesici özeti');const stateBefore=state();expect(state()).toEqual(stateBefore);await Promise.all([deliverOne(env),deliverOne(env)]);expect(sendMessage).toHaveBeenCalledTimes(1);for(let i=1;i<dkb.length;i++)await deliverOne(env);await runEveningSummaries(env,at);expect(state().status).toBe('completed');const summary=await getEveningDkbSummary(env,'2026-09-30',at);expect(summary.availability).toBe('available');expect(summary.all_pages_sent).toBe(true);expect(summary.source_data_at).toBeNull();expect(sendMessage).toHaveBeenCalledTimes(dkb.length);expect(rows().some(r=>r.id.includes(':pay:'))).toBe(false);});
 it('never reclaims an expired scheduled sending lease or releases PAY after uncertain delivery',async()=>{await runEveningSummaries(env,at);sql.prepare("UPDATE telegram_outbox SET status='sending',lease_until=?,attempts=1").run(at-1);await deliverOne(env);expect(sendMessage).not.toHaveBeenCalled();expect(rows()[0].status).toBe('blocked');await runEveningSummaries(env,at);expect(state().status).toBe('needs_attention');await runEveningSummaries(env,at+60000);expect(rows()).toHaveLength(1);});
 it.each([new Error('timeout'),new TelegramError(500),new TelegramError(429,5),new TelegramError(403)])('stops on a scheduled send error without retry or PAY enqueue',async(error)=>{await runEveningSummaries(env,at);sendMessage.mockRejectedValue(error);await deliverOne(env);await deliverOne(env);expect(sendMessage).toHaveBeenCalledTimes(1);await runEveningSummaries(env,at);expect(state().status).toBe('needs_attention');expect(rows().some(r=>r.id.includes(':pay:'))).toBe(false);});
 it('does not resend after Telegram success but receipt persistence fails',async()=>{await runEveningSummaries(env,at);const batch=env.DB.batch;env.DB.batch=async()=>{throw new Error('receipt write failure');};await expect(deliverOne(env)).rejects.toThrow('receipt write failure');env.DB.batch=batch;vi.setSystemTime(at+91000);await deliverOne(env);expect(sendMessage).toHaveBeenCalledTimes(1);await runEveningSummaries(env,at+91000);expect(state().status).toBe('needs_attention');});
 it('halts missing pages and never regenerates after a crashed preparation lease',async()=>{await runEveningSummaries(env,at);sql.prepare('DELETE FROM telegram_outbox').run();await runEveningSummaries(env,at);expect(state().error).toBe('page_manifest_mismatch');const key=summaryStateKey(env.TELEGRAM_CHAT_ID,'2026-09-30'),r=state();sql.prepare('UPDATE system_state SET value=? WHERE key=?').run(JSON.stringify({...r,status:'preparing_dkb',lease_until:at-1}),key);await runEveningSummaries(env,at);expect(state().error).toBe('preparation_lease_expired');expect(rows()).toHaveLength(0);});
 it('blocks unsent pages after 21:00 and never starts PAY outside the window',async()=>{await runEveningSummaries(env,at);const late=Date.parse('2026-09-30T18:00:00Z');vi.setSystemTime(late);await runEveningSummaries(env,late);expect(state().error).toBe('delivery_window_expired');expect(rows().some(r=>r.id.includes(':pay:'))).toBe(false);});
 it('preserves more than ten stocks, every source and texts beyond 50000 characters with explicit pagination',async()=>{manyBreakers();await runEveningSummaries(env,at);const key=summaryStateKey(env.TELEGRAM_CHAT_ID,'2026-09-30'),r=state();sql.prepare('DELETE FROM telegram_outbox').run();const payloads=Array.from({length:25},(_,i)=>JSON.stringify({text:'page '+i+' '+ 'X'.repeat(2900),plain:true}));sql.prepare('UPDATE system_state SET value=? WHERE key=?').run(JSON.stringify({...r,dkb_pages:25}),key);for(let i=0;i<25;i++)sql.prepare("INSERT INTO telegram_outbox(id,kind,payload,status,first_seen_at,available_at,message_id,sent_at) VALUES (?,'action_reply',?,'sent','2026-09-30',0,123,'2026-09-30')").run(scheduledSummaryId(env.TELEGRAM_CHAT_ID,'2026-09-30','dkb')+':'+String(i).padStart(4,'0'),payloads[i]);const first=await getEveningDkbSummary(env,'2026-09-30',at);expect(first.full_text.length).toBeGreaterThan(50000);expect(first.next_page_offset).toBe(20);expect(first.pagination_complete).toBe(false);const last=await getEveningDkbSummary(env,'2026-09-30',at,20,500);expect(last.next_page_offset).toBeNull();expect(last.next_source_offset).toBeNull();expect(last.pagination_complete).toBe(true);expect([...first.pages,...last.pages].map(p=>p.text)).toEqual(payloads.map(p=>JSON.parse(p).text));let all=[];for(let offset=0;offset!==null;){const part=await getEveningDkbSummary(env,'2026-09-30',at,0,offset);all.push(...part.source_records);offset=part.next_source_offset;}expect(all).toHaveLength(550);expect(new Set(all.map(r=>r.disclosure_id)).size).toBe(550);});
 it('legacy manual summaries retain their existing retry policy',async()=>{sql.prepare("INSERT INTO telegram_outbox(id,kind,payload,status,first_seen_at,available_at) VALUES ('day-summary:dkb:123:55:0000','action_reply','{\"text\":\"manual\",\"plain\":true}','pending','2026-09-30T17:30:00Z',0)").run();sendMessage.mockRejectedValue(new Error('legacy timeout'));await deliverOne(env);expect(sql.prepare('SELECT status FROM telegram_outbox').get().status).toBe('pending');});
});
