import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {database} from './db-harness';
import {GENEL_KURUM_TEMPLATE_ID,getReaderJob,listReaderJobs} from '../src/commands/reader';
import {startCommandWorkflow,getCommandWorkflow,refreshActiveWorkflow,RUN_MODES} from '../src/commands/workflows';
const now=Date.parse('2026-09-30T12:00:00Z'),requested=new Date(now).toISOString();
describe('explicit single Genel Kurum workflow',()=>{
 it('preserves the actual user-added bot, exact /kurum and one-step template',()=>{const {sql}=database();try{const row=sql.prepare('SELECT * FROM command_templates WHERE id=?').get(GENEL_KURUM_TEMPLATE_ID);expect(row.name).toBe('genel kurum');expect(JSON.parse(row.steps_json)).toEqual([{botUsername:'ucretsizderinlikbot',command:'/kurum',delaySeconds:3}]);}finally{sql.close();}});
 it('starts only Genel Kurum, deduplicates the same request, reads complete plain text and finishes the exact job',async()=>{const {sql,env}=database();env.COMMAND_RUN_ENABLED='true';try{const run=await startCommandWorkflow(env,'owner','genelkurum','genel-kurum-one-time-fixture',requested,now);expect(run.jobs).toHaveLength(1);expect(run.mode).toBe('genelkurum');expect(run.jobs[0]).toMatchObject({template:'genelkurum',template_id:GENEL_KURUM_TEMPLATE_ID,expected_steps:1,status:'queued'});const job=sql.prepare('SELECT * FROM command_jobs WHERE id=?').get(run.current_job_id);expect(JSON.parse(job.steps_json)).toEqual([{botUsername:'ucretsizderinlikbot',command:'/kurum',delaySeconds:3}]);expect((await startCommandWorkflow(env,'owner','genelkurum','genel-kurum-one-time-fixture',requested,now)).workflow_id).toBe(run.workflow_id);sql.prepare("INSERT INTO command_results(job_id,step_index,bot_username,command,response_text,response_kind) VALUES (?,0,'ucretsizderinlikbot','/kurum',?,'text')").run(job.id,'Bank of America\nAlış: 123\nİş Yatırım\nSatış: 456');sql.prepare("UPDATE command_jobs SET status='completed',finished_at='2026-09-30 12:01:00' WHERE id=?").run(job.id);await refreshActiveWorkflow(env,now+61000);const done=await getCommandWorkflow(env,'owner',run.workflow_id,now+61000);expect(done.status).toBe('completed');expect(done.global_lock_held).toBe(false);const read=await getReaderJob(env,job.id,now+61000);expect(read.result_set_complete).toBe(true);expect(read.full_text).toContain('Bank of America\nAlış: 123\nİş Yatırım\nSatış: 456');expect(read.source_data_at).toBeUndefined();expect(read.results[0].media_state).toBe('none');expect((await listReaderJobs(env,'genelkurum',10)).jobs[0].id).toBe(job.id);}finally{sql.close();}});
 it('market_round still contains only Terane then Kurum and requires the separate run flag',async()=>{const {sql,env}=database();try{await expect(startCommandWorkflow(env,'owner','genelkurum','genel-kurum-flag-off-fixture',requested,now)).rejects.toMatchObject({code:'command_runner_disabled'});env.COMMAND_RUN_ENABLED='true';const run=await startCommandWorkflow(env,'owner','market_round','market-round-unchanged-fixture',requested,now);expect(run.jobs.map(j=>j.template)).toEqual(['terane','kurum']);expect(RUN_MODES).toContain('genelkurum');}finally{sql.close();}});
 it('migration preserves all old workflow fields and unique owner/global active locks',()=>{const sql=new DatabaseSync(':memory:');try{sql.exec(readFileSync('migrations/0021_command_workflows.sql','utf8'));sql.prepare("INSERT INTO command_workflows(id,owner_sub,request_key,mode,status,snapshots_json,current_index,current_job_id,requested_at,accepted_at,start_before,deadline_at,error) VALUES ('existing','owner','existing-key','market_round','running','[]',1,'job','request','accept','start','deadline','preserved')").run();const before=sql.prepare('SELECT * FROM command_workflows').get();sql.exec('BEGIN');sql.exec(readFileSync('migrations/0023_genel_kurum_workflow_mode.sql','utf8'));sql.exec('COMMIT');expect(sql.prepare('SELECT * FROM command_workflows').get()).toEqual(before);expect(()=>sql.prepare("INSERT INTO command_workflows SELECT 'duplicate',owner_sub,'different-key',mode,status,snapshots_json,current_index,current_job_id,requested_at,accepted_at,start_before,deadline_at,finished_at,error FROM command_workflows").run()).toThrow();sql.prepare("UPDATE command_workflows SET status='completed'").run();expect(()=>sql.prepare("INSERT INTO command_workflows SELECT 'duplicate',owner_sub,request_key,mode,status,snapshots_json,current_index,current_job_id,requested_at,accepted_at,start_before,deadline_at,finished_at,error FROM command_workflows").run()).toThrow();sql.prepare("UPDATE command_workflows SET mode='genelkurum'").run();expect(()=>sql.prepare("UPDATE command_workflows SET mode='arbitrary'").run()).toThrow();}finally{sql.close();}});
});
